services:
  playwright-test:
    image: playwright-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run test:ci
    environment:
      CI: true
    volumes:
      - ./allure-results/:/app/allure-results
      - ./test-results/:/app/test-results
